name: Build with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 更新到 v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3  # 更新到 v3
      with:
        java-version: '1.8'
        distribution: 'temurin'  # 指定 Java 发行版

    - name: Run Maven build
      run: mvn clean test

